POST /register HTTP/1.1
Host: localhost:8888
Content-Type: application/json

{
    "fullname": "Vincentius",
    "email": "vincent@mail.com",
    "password": "12345"
}

###

POST /login HTTP/1.1
Host: localhost:8888
Content-Type: application/json

{
    "email": "vincent@mail.com",
    "password": "12345"
}

###

GET /users HTTP/1.1
Host: localhost:8888
Content-Type: application/json

###

GET /users/1 HTTP/1.1
Host: localhost:8888
Content-Type: application/json

###

PATCH /users/1 HTTP/1.1
Host: localhost:8888
Content-Type: application/json

{
    "address": "Bandung"
}

###

DELETE /users/1 HTTP/1.1
Host: localhost:8888
Content-Type: application/json


